### ISSUE TITLE
分岐の挙動がおかしい

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#100]
#33 関連
[079 るてしキスキしてる.zip](https://github.com/Tatelier/Tatelier/files/6493360/079.zip)
079W るてしキスキしてる【ネタ双打】裏譜面
次郎と若干違っていますので、再度ご確認お願いします。

**Comment by pansystar** [comment]
#99 の対応によって動作するようになったかもしれません。
v0.4.1で公開しますので、改めて確認いただきたく思います。

ただ、描画順アルゴリズムが間違っている影響で、音符の重なり方や小節線が無駄に多く描画されています。それに関してはv0.5.0までに治せるよう努めます。

**Comment by pansystar** [comment]
次郎のように分岐時に上下に動きはしませんが、処理をあわせることはできました。
v0.5.0で公開(v0.4.1に入ります。)
