### ISSUE TITLE
編集画面でうまく再生できない時がある

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#104]
一応譜面おいておきます
https://ux.getuploader.com/LoveLive_Jiro/download/74
説明しずらいので動画をご覧ください。
https://user-images.githubusercontent.com/77183438/120491216-0350de00-c3f4-11eb-9303-5e9fbb2c5190.mp4

**Comment by pansystar** [comment]
ひどいですね...

処理を確認し、対応します。

**Comment by pansystar** [comment]
上記指摘の通りでした。

対応完了
