### ISSUE TITLE
記録に応じて王冠の画像を描画して欲しい

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#109]
#44 関連

**Comment by pansystar** [comment]
現状、起動時間短縮などの兼ね合いで立ち上げ時にセーブデータの読み込みはしていない。

MainConfigの選曲設定で立ち上げ時の挙動を設定できる項目を追加し対応する。

1. 譜面を選択したタイミングでセーブデータをロードし、王冠などのアイコンを描画する。別の譜面に移動した際に、そのデータはクリアする。(デフォルト)
※起動時間(短) &メモリ使用量(最小)

1. 譜面を選択したタイミングでセーブデータをロードし、王冠などのアイコンを描画する。別の譜面に移動してもデータクリアは行わない。
※起動時間(短) & メモリ使用量(徐々に大)

1. 立ち上げ後に裏側で全譜面のセーブデータをロードし、逐次的に王冠などのアイコンを描画する。
※セーブデータ読込中でも選曲ができる。
※起動時間(短) & メモリ使用量(大)

1. 立ち上げ前に全てのセーブデータをロードする。
※起動時間(長) & メモリ使用量(大)

**Comment by Reiya0917milk** [comment]
一旦close
