### ISSUE TITLE
動作確認情報

### ISSUE THREAD

**Issue by pansystar** [Tatelier/Tatelier#11]
動作確認情報をまとめています。
Tatelierを遊びたくて対応スペックが気になる方は、こちらの情報をご覧ください。

|  CPU  |  GPU  | 結果
| ---- | ---- | ---- |
|  i3-4160 3.6GHz |  Intel(R) HD Graphics 530 | 遊べた |

**Comment by gonii258** [comment]
CPU
corei7 9700 3.0GHz
メモリ16GB
RTX2060Super

正常に遊ぶことができました

**Comment by Takkkom** [comment]
cpu=intel i5 3470s 2.90gb
ram=16gb ddr3
gpu=gtx1050ti 4gb
os=windows10 pro 64bit

**Comment by Takkkom** [comment]
それと遊べました!

**Comment by castella-cake** [comment]
| CPU | GPU | 結果 |
----|----|---- 
| Ryzen 5 3500 | RX590 | 問題なし

**Comment by TamaTamAGo** [comment]
​CPU i3 9100F
 GPU GTX1650 
結果 遊べた

**Comment by iron01** [comment]
| CPU | GPU | 結果 |
| Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz | Intel(R) HD Graphics 530 | 動いた

**Comment by iron01** [comment]
| CPU | GPU | 結果 |
| Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz | Intel(R) HD Graphics 530 | 動いた |

**Comment by iron01** [comment]
|CPU|GPU|結果|
----|----|---- 
|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz|Intel(R) HD Graphics 530|動いた|

**Comment by TamaTamAGo** [comment]
| CPU | GPU | 結果 |
----|----|---- 
| i3 9100F | GTX1650 | 遊べた

**Comment by Reiya0917milk** [comment]
| CPU | GPU | 結果 |
----|----|---- 
|Corei54590 |不明 | 正常に動作しました

**Comment by Reiya0917milk** [comment]
サブPC
| CPU | GPU | 結果 |
----|----|---- 
| Intel(R) Core(TM) i7-3610QM | Intel(R) HD Graphics 4000 | 問題なし

**Comment by pansystar** [comment]
ひとまずクローズ

**Comment by Reiya0917milk** [comment]
| CPU | GPU | メモリ| 結果 |
----|----|---- |---- 
|AMD Ryzen 9 5900HX|AMD Radeon(TM) Graphics|16GB|問題なし
