### ISSUE TITLE
ミスサウンドの再生

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#112]
判定が見過ごし不可、または叩いて不可のとき、音を鳴らす。

**Comment by pansystar** [comment]
@Reiya0917milk 
連続不可時は鳴らさない認識であってますか？

**Comment by Reiya0917milk** [comment]
連続負荷の時も再生をお願いします。

**Comment by Reiya0917milk** [comment]
音源ファイルをPlayConfigで指定できるようにお願いします。

**Comment by pansystar** [comment]
@Reiya0917milk すいません。ミスサウンドってどんな感じになるのでしょうか？
switch版の太鼓では鳴らなかったので、参考になる動画を教えていただきたいです。

**Comment by Reiya0917milk** [comment]
koiotoさんと同じようにして欲しいです。
https://github.com/Koioto/MissSound/commit/cd39a0ed0bad8241cbc199a1cf19c8f163e193fe

**Comment by pansystar** [comment]
対応完了。
