### ISSUE TITLE
レジストリエディタでファイル指定で起動しようとするとエラーが発生する

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#116]
#46 関連
![IMG_20210617_214341](https://user-images.githubusercontent.com/77183438/122399132-7d1cc600-cfb5-11eb-932d-e0ba2ecd7658.jpg)

**Comment by pansystar** [comment]
本現象、現在も発生しますでしょうか？

**Comment by Reiya0917milk** [comment]
現在でも不具合を確認しました。
レジストリエディタで起動するとこのような現象になりました。
https://www.wannko.net/windows10/etc/lodesk.html

**Comment by pansystar** [comment]
カレントディレクトリを変更する処理のタイミングにずれがあり、本現象が発生しておりました。
修正したものを突発開発版として作成しましたので、ご都合の良いタイミングで確認いただきたく思います。

https://tatelier.pansystar.net/dist/tatelier/v0.7.1d1/Tatelier-v0.7.1d1-Release-x64.zip

**Comment by Reiya0917milk** [comment]
問題ありませんでした。修正ありがとうございます。
