### ISSUE TITLE
難易度の決定後、演奏画面に移動するまで入力を受け付けないようにする

### ISSUE THREAD

**Issue by castella-cake** [Tatelier/Tatelier#12]
難易度の決定後、すぐに別の難易度を選択すると演奏画面で幕が完全に開きません。
ポーズメニューから選曲画面へ移動しても幕はそのままで、
その状態で曲を決定し難易度選択画面へ移動するとカーソル以外が動かず難易度の決定ができません。

**Comment by pansystar** [comment]
対応完了 v0.2.0で公開
