### ISSUE TITLE
HBSCROLL雑記

### ISSUE THREAD

**Issue by pansystar** [Tatelier/Tatelier#120]

**Comment by pansystar** [comment]
判定枠を過ぎたら処理をしないという機構があるのは間違いない。

**Comment by pansystar** [comment]
判定枠に近い方から処理することで、昨日の配信で赤符が瞬間移動した理由になる。

**Comment by pansystar** [comment]
Measureやbpmの処理は、それがカレントに来るまで正しく処理してないと思われる。

**Comment by pansystar** [comment]
判定を過ぎた音符は通常譜面と同じ挙動になる必要がある。
↓

**Comment by Reiya0917milk** [comment]
[ここ](https://wikiwiki.jp/ryuou2gou/%E7%AB%9C%E7%8E%8B%E3%81%AE%E3%82%AE%E3%83%9F%E3%83%83%E3%82%AF%E8%AD%9C%E9%9D%A2%E3%81%AE%E4%BD%9C%E3%82%8A%E6%96%B9%E8%AC%9B%E5%BA%A7%E3%82%A1%EF%BC%81)
のサイトを見ながら少しやって見ました。

瞬間移動
#BPMCHANGE 7500～120000//極度にBPMを上げて急に譜面を出現させるという仕組み。上げすぎ厳禁！
#MEASURE ○/4←どんだけ瞬間移動させるか指定
,
--
逆走
#BPMCHANGE -200
#MEASURE -4/8 　//←これがなかったり、値が+だったりするとフルコンボ不可能譜面になるので注意
222222222222,
--
逆走(通り過ぎて戻る)
//通り過ぎる
#BPMCHANGE 200
#MEASURE 1/8
,
//戻る
#BPMCHANGE -200
#MEASURE -1/8
,
#BPMCHANGE 200
#MEASURE 1/4
1111,

**Comment by pansystar** [comment]
小節線上に音符があるかどうかで挙動が変わる

**Comment by pansystar** [comment]
## また脱線
BPMが負でMEASUREが正のときに
MEASUREを負の値へ変更したときの次郎の挙動を確認してみた。

**Comment by Reiya0917milk** [comment]
補足参考になるかどうかはわかりませんが

本家太鼓_達人はBPMを変えても区間毎に速度が決まっているので流れる速度に差が生じ、視認できます。
一方HBSCROLLはBPMを変更した区間に到達するまではBPMの変化を視認できません。この「区間に到達するまで流れる速度が変化しない」ことを利用したのがギミック譜面です。

**Comment by pansystar** [comment]
- BPMからBPMまでの音符を保持する処理は作成完了
- MEASUREやSCROLLSPEEDもひとまず作成
- ここから瞬間移動を作っていく。

**Comment by pansystar** [comment]
また何かあればReopenして記述する。
