### ISSUE TITLE
HBSCROLLで次郎と挙動が異なる

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#124]

**Comment by pansystar** [comment]
ありがとうございます。
1つ1つ確認していきます！

**Comment by pansystar** [comment]
追記中

@Reiya0917milk 
以下の不具合で足りないor違う場合は指摘ください。

## 始まりは君の空
- Rollの描画処理に不具合あり。他は大丈夫だと思いました。

**Comment by Reiya0917milk** [comment]
v0.6.3にて動作確認をした結果です。
・始まりは君の空
最初に連打が表示される (次郎では表示されない音源開始後に表示)
・SELF CONTROL
スクロールスピードに関しては問題なし 連打が伸びるときに切れてしまう
・Believe Again
譜面が突然現れる挙動になる
・Fantastic Departure!
問題なし
・アンパンマンのマーチ
1番のBメロの挙動は問題なし

**Comment by pansystar** [comment]
- 始まりは君の空
  - 指摘の挙動を確認
  - 対応方法を検討
  - [ ] 対応完了
- SELF CONTROL
  - 後日確認
- Believe Again
  - 次郎と照らし合わせたものの、指摘の挙動を確認できなかった...
-

**Comment by Reiya0917milk** [comment]
Believe Againについては問題ありませんでした失礼しました。 とりあえずクローズします修正ありがとうございます。

**Comment by pansystar** [comment]
さまざまな譜面の調査・報告
本当にありがとうございます。

現在見つかっている不具合もどうにか方法を見つけて対応していきます。
