### ISSUE TITLE
レベルにコメント文をパースしていると選曲画面に移行せずエラーが発生する

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#125]
[Mwfyuma Perustallora.zip](https://github.com/Tatelier/Tatelier/files/6836254/Mwfyuma.Perustallora.zip)

**Comment by pansystar** [comment]
LEVELのコメント文をパースしていることが原因。

**Comment by Reiya0917milk** [comment]
次郎では再生できているので対応お願いします。

**Comment by pansystar** [comment]
v0.6.3で対応済

**Comment by Reiya0917milk** [comment]
動作確認済
