### ISSUE TITLE
#HBSCROLL がある譜面にて、音符が表示されない

### ISSUE THREAD

**Issue by fenedoragon** [Tatelier/Tatelier#128]
音源、譜面は再生されますが、音符が表示されませんでした。
また、＃DELAYのところでは、譜面停止せず、SCROLLが-の通常音符も表示されませんでした

譜面　https://www.youtube.com/watch?v=izzerM0-JN8

**Comment by pansystar** [comment]
DELAYの挙動は現在未対応のため想定通り
#119
その他検証中...

**Comment by pansystar** [comment]
SCROLLがマイナスのとき、元々作っていた最適化処理の影響で描画されない処理になっていました。

暫定的にSCROLLがマイナスのときは描画する処理に変更し、
今後最適化していく中で恒久対応を進めます。

また、本件確認中に風船音符の挙動に怪しい部分があったため合わせて修正しました。

v0.11.2で対応完了
