### ISSUE TITLE
特定の譜面を読み込むとクラッシュする

### ISSUE THREAD

**Issue by Takkkom** [Tatelier/Tatelier#129]
譜面が配布されているyoutubeの動画はこちらです 
https://www.youtube.com/watch?v=LkF2JzXGeFo

どうやら音声は読み込めているので譜面の
パーサーの不具合かと(勝手な予測ですが)

**Comment by pansystar** [comment]
裏鬼のみの譜面に対して選曲時に表鬼が選択できてしまうことで本現象が発生。

v0.7.0で遊ぶ場合は裏鬼を選択して、本現象を回避してください。

**Comment by pansystar** [comment]
譜面内容を見たところ、LEVELが2回宣言されており、その間でCOURSEが宣言されている。

譜面側のミスなので対応は後手に回すが、次郎の挙動と合わせられるよう検討してみる。

**Comment by Reiya0917milk** [comment]
@pansystar 
次郎で確認してみたらCOURSEの所のレベルが反映されていました。COURSEが記載されていない所でレベルを宣言しても反映されていなかったので動作をパスするようにすればいいかもしれません。
又、COURSE:Editを削除しても同じ挙動になりました。
