### ISSUE TITLE
セーブデータがない曲でdecryptコマンドを入れるとエラーが発生する

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#137]
エラーではなくて警告を出すようにする感じでどうでしょうか？

**Comment by pansystar** [comment]
この例外は想定していない挙動でした。
※デバッグ環境が整理されていて気づいてませんでした。

修正します。

**Comment by pansystar** [comment]
セーブデータがない際にSaveフォルダを作成していないことで例外が発生していました。

https://tatelier.pansystar.net/dist/tatelier/v0.7.1d2/Tatelier-v0.7.1d2-Release-x64.zip

**Comment by Reiya0917milk** [comment]
返信が遅くなり申し訳ありません。動作確認をしてみたところ不明なコマンドと表示されています。でーたのさくせいはできているようです。
![image](https://user-images.githubusercontent.com/77183438/129900446-fa044028-0081-42f0-8ae0-d7f851128fee.png)

**Comment by pansystar** [comment]
確認ありがとうございます。
別で作業していたコマンド処理の修正に不具合があったようです。

次回リリースまでに修正をしておきます!

**Comment by Reiya0917milk** [comment]
問題なし
