### ISSUE TITLE
​音源終了後に一時停止して再開するとリザルト画面に移行せず音源が再開される

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#142]

**Comment by pansystar** [comment]
#83 と似ている現象の模様。
暫定的な対処をすすめる。

**Comment by pansystar** [comment]
すいません。以前自分が所持していた譜面でも同様の現象を確認していたのですが、その譜面がどれなのかわからなくなってしまいました...

恐れ入りますが、該当の譜面をご教示いただけますでしょうか？

**Comment by Reiya0917milk** [comment]
ほとんどの曲が起こっています。が一応一曲だけ送ります
https://ux.getuploader.com/LoveLive_NSD_Jiro/download/84

**Comment by pansystar** [comment]
ありがとうございます。

音声再生部の処理を一部変更していたのですが、それによって本現象が解消された可能性があります。
上記譜面で現象が発生しませんでした。

突発開発版を作成しましたので、お時間ある際に他の譜面で確認いただきたく思います。
※このバージョンの処理は、今週末にリリース予定のv0.9.0にも盛り込み予定です。

https://tatelier.pansystar.net/dist/tatelier/v0.8.0d1/Tatelier-v0.8.0d1-Release-x64.zip

**Comment by Reiya0917milk** [comment]
多分問題ないです。ありがとうございます。
