### ISSUE TITLE
同じ行に小節区切りカンマが2連続しているとき、そのカンマを無視する。

### ISSUE THREAD

**Issue by Yutamsub** [Tatelier/Tatelier#146]
先日作った譜面をTatelierで読み込んでみた所、何故かうまく読み込まれず正常に動作しませんでした。
自分の譜面の書き方が悪いかもです。

録画したものはこちらです。
https://www.youtube.com/watch?v=sL86axHvTGI

譜面です(音源抜き)
https://ux.getuploader.com/yutam_humen/download/23

**Comment by Reiya0917milk** [comment]
10000020100020001000222210002000,,
の部分に,が二つあることが原因の可能性がありますのでとりあえず一つ削除して回避してみてください。

**Comment by Yutamsub** [comment]
わかりました。

**Comment by pansystar** [comment]
カンマが連続している際、次郎だと無視するのですね...

その仕様に合わせるよう処理を変更します。

**Comment by pansystar** [comment]
対応完了
上記譜面で動作確認済み
