### ISSUE TITLE
mp3でのみ同じ音源を参照している別の曲を交互に変更すると極端に処理落ち(フリーズ)する

### ISSUE THREAD

**Issue by Takkkom** [Tatelier/Tatelier#148]
例 
fumen1.tja
fumen2.tja
song.mp3 

の中身フォルダが存在したとして
fumen1.tja、fumen2.tja 
のファイルどちらも音源は 
song.mp3 
参照したとして 
その曲同士を選曲画面で交互に変更すると極端に処理落ちを起こす 
そして何回も早く交互に変更するとError画面も表示されずに
アプリケーションがフリーズして落ちる 。

そしてmp3ファイルの音質が良いほどフリーズする時間が長くなり
落ちる確率が上がる
何故かoggなどの場合はフリーズしたり落ちたりすることはない。

**Comment by pansystar** [comment]
音源ロード処理はDXライブラリに委ねているので、外側から制御できるかわからない。
ひとまず検討を進めることにする。

**Comment by pansystar** [comment]
指摘いただいた現象は確認できなかったが、mp3音源のときに再生が途中で停止したり不安定になっていることはわかった。
ただ、上記の通りDxライブラリに委ねているため、暫定的な対処を改めて検討する。

例)
* mp3音源をogg音源に変換してから再生する (読込速度が大幅に低下すると思われるが...)

**Comment by pansystar** [comment]
Dxlibでmp3を読み込むときは、PCにインストールされているコーデックを利用することがわかりました。oggはdxlibに含まれているため、環境に依存せず安定した動作をするそうです。

そうなると、mp3をoggに変換して再生する方が安定しそうなので、その方向で対応を進めていきます。

※別チケットで対応

@Takkkom 
以上でよろしければ本チケットをcloseしてください。
