### ISSUE TITLE
演奏結果が保存されない

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#158]

**Comment by pansystar** [comment]
演奏結果は保存されているものの、
結果画面から選曲画面に遷移した際にプレイヤーの情報を再取得しておりませんでした。

検証用のv0.11.2d1を作成しましたので、ご確認いただきたく思います。
https://tatelier.pansystar.net/

**Comment by pansystar** [comment]
すいません。帰宅後確認しアップします。

**Comment by pansystar** [comment]
v0.11.2d2をアップ致しました。

移植作業時の漏れがありました。

よろしくお願いします。

**Comment by Reiya0917milk** [comment]
保存できませんでした
![image](https://user-images.githubusercontent.com/77183438/152998538-5a45c713-e9de-498f-a43a-85f25fa560b2.png)

**Comment by pansystar** [comment]
思ってた事象と違うみたいです....

「演奏結果を保存できませんでした。」の文言は、演奏結果保存時にフォルダ作成に失敗したときに表示される文言になっています。(それも抽象的でおかしな挙動ですが...)

以前ご指摘いただいた際のシンクライアントPCで利用されているという認識でよろしいでしょうか？
https://github.com/Tatelier/Tatelier/issues/46

System32内にフォルダを作る権限がないことで発生した可能性があるため、セーブデータの保存先をMainConfigから指定できるよう、実装を進めたいと思います。

一時的な解決法としましては、Tatelier.exeを管理者権限で立ち上げると動作する可能性があります。

ちなみにですが、最初の頃は同じ環境下でも問題なく保存されてたでしょうか？

保存されていた場合は改めて検討します

**Comment by pansystar** [comment]
2/9の夜にログを強化したd3版を作成しますので、改めて連絡いたします。

**Comment by Reiya0917milk** [comment]
管理者権限で実行してみましたが変わりませんでした。
最初の頃はちゃんと保存できていました。
シンクライアントPCではありません

**Comment by pansystar** [comment]
d3版を作成しました。

演奏結果保存時に失敗すると以下のダイアログが表示されます。

↓は強制的に例外になるような処理を入れています。
![image](https://user-images.githubusercontent.com/17560479/153210823-45ef1109-1c92-47f0-9d37-61d03c3d1b41.png)


ファイルパスと例外(NotSupportedException etc.)が表示されますので確認いただけますでしょうか？

**Comment by pansystar** [comment]
Tatelierのパス指定処理の不具合です。申し訳ございません！

修正します。

**Comment by pansystar** [comment]
対応完了
v0.12.0でリリース
