### ISSUE TITLE
演奏開始直後に幕が静止する

### ISSUE THREAD

**Issue by yutam1023** [Tatelier/Tatelier#18]
難易度を選んで演奏開始した直後にドンやカッを押すと幕が静止して一種の縛りプレイみたいになる
![image](https://user-images.githubusercontent.com/71923389/106356290-f8047d80-6341-11eb-98d7-996d72d28a07.png)
![image](https://user-images.githubusercontent.com/71923389/106356229-84fb0700-6341-11eb-9487-d34bef325cb8.png)
また、そのあとは曲が遊べなくなる。(再機動したら治る)
![image](https://user-images.githubusercontent.com/71923389/106356309-17030f80-6342-11eb-9015-bcac2090d7bf.png)

**Comment by pansystar** [comment]
#12 
と同じバグのため、クローズ
