### ISSUE TITLE
歌詞表示(*.lrc)

### ISSUE THREAD

**Issue by pansystar** [Tatelier/Tatelier#24]
https://www.sony.jp/support/walkman/tips/sync-lyrics/wm.html#cnt01

**Comment by Reiya0917milk** [comment]
歌詞ファイルを指定する方法としてTJAファイル内に LYRICFILE:hog.lrc と記載する。もし段位の実装予定があれば一曲ずつ指定できるようにしてほしいです。又ファイル名にカンマが含まれている場合、円マークでエスケープできるようにしてほしいです段位の時にファイルが分かれてしまう為

**Comment by Reiya0917milk** [comment]
参考資料
https://github.com/Koioto/SyncLyrics/commit/10035a4c4bd455b06425f2b348d7964d2f3e7c7a

**Comment by pansystar** [comment]
対応してみたのですが、想定している動作になっているか確認いただけますでしょうか？
※お時間があるときで問題ないです。

https://tatelier.pansystar.net/dist/dbg/Tatelier-v0.3.1d.zip

**Comment by pansystar** [comment]
![image](https://user-images.githubusercontent.com/17560479/114276481-b854c300-9a61-11eb-8365-8fe71bbf4563.png)

**Comment by pansystar** [comment]
補足です。
lrcファイルは譜面ファイル(*.tja)と同じ名前でないと読み込まれません。
先頭に数字がついていたり、半角スペースに違いがあっても読まれないので注意してください。
![image](https://user-images.githubusercontent.com/17560479/114276855-79277180-9a63-11eb-8f26-b4793e494ec6.png)

また、上記リンクのTatelierは改良中による不具合が入っています。ご了承ください。

**Comment by Reiya0917milk** [comment]
同じ名前にしているのですがエラーが発生してしまいます
![image](https://user-images.githubusercontent.com/77183438/114291175-49f31d80-9ac0-11eb-9851-277dc8826333.png)

**Comment by Reiya0917milk** [comment]
とりあえずは大丈夫です。ありがとうございます。

**Comment by pansystar** [comment]
可能です。

歌詞も編集できるほうがいいですね。
検討を勧めます。

**Comment by Reiya0917milk** [comment]
lrcの読み込みに関してですが、譜面ファイル名と同じでないと読み込めないとありましたが可能であれば音源ファイルの名前で読み込めるようにすることはできないでしょうか？

**Comment by pansystar** [comment]
確かに音源ファイルに紐づくのが一般的ですね。そうします。

**Comment by pansystar** [comment]
「LYRIC:」で歌詞ファイル名を指定して利用できる処理を作成
上記定義がない場合は、音源ファイル名から歌詞ファイルを取得する処理を作成

v0.4.0で公開
