### ISSUE TITLE
BPMが負(マイナス)の時にフリーズする

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#27]
BPMが負(マイナス)の時にフリーズするバグが発生します。

**Comment by pansystar** [comment]
現象確認

**Comment by pansystar** [comment]
BPMのみを暫定的に対応
Measureなどが不正値の場合も同様の現象が発生するか、別の事象が発生する可能性が高いため調査&改修をv0.3.0以降で実施する
![image](https://user-images.githubusercontent.com/17560479/106907874-0f78a780-6742-11eb-9c3d-5a495c9ff49a.png)

**Comment by pansystar** [comment]
info → warningに格上げ
![Uploading image.png…]()
