### ISSUE TITLE
最新版に移行したら認証に失敗しましたと表示される

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#28]
最新版に移行したら認証に失敗しましたと表示されました。ファイルを入れなおしても起動できませんでした。エラーコード 0x00030101

**Comment by Reiya0917milk** [comment]
起動できました申し訳ありませんでした。

**Comment by pansystar** [comment]
もし同じエラーが出た際は改めて連絡いただけると幸いです。
