### ISSUE TITLE
曲を選択するとエラーが発生する

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#29]
分岐曲?を選択するとエラーが発生します。エラーが出る譜面置いておきます。
https://ux.getuploader.com/LoveLive_NSD_Jiro/download/44

**Comment by pansystar** [comment]
p と 値の間に半角スペースがないのですが、他のソフトではこの状態でも読み込みができるのでしょうか？

![image](https://user-images.githubusercontent.com/17560479/106880835-30c89c00-6720-11eb-82fd-439b5ddd94cf.png)

**Comment by Reiya0917milk** [comment]
TJAP3の譜面分岐修正版の方で読み込みできます。
一応参考資料置いておきます
https://github.com/Akasoko-Master/TJAPlayer3/commit/98a861247c15f6abd1b4bc3413e3a35e74921523

**Comment by pansystar** [comment]
譜面側の定義ミスを許容してるんですね...

ありがとうございます。

v0.2.0で対応

**Comment by pansystar** [comment]
対応完了
