### ISSUE TITLE
命令の最後に,が残ってしまっているときの対応

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#33]
分岐はされているがゲージが一気に溜まってしまう不具合があるため
譜面 079W るてしキスキしてる【ネタ双打】.tja
https://ux.getuploader.com/LoveLive_Jiro/download/79
https://github.com/Mr-Ojii/TJAPlayer3-f/commit/2619374625f3352c1d1119ce8baa0988eb5aed77

**Comment by pansystar** [comment]
いつもありがとうございます！

確認します。

**Comment by pansystar** [comment]
現象を確認しました。
分岐の挙動も怪しい部分があるように見えたので続けて調査します。

**Comment by pansystar** [comment]
ドンカツの総数取得処理のミスで本現象が発生していました。

修正完了
v0.3.0で公開
