### ISSUE TITLE
VPNを設定していると認証エラーが発生する

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#36]
VPNを設定していると認証エラーが発生します。修正可能であればお願いします。無理な場合はVPNの解除の警告などを表示してほしいです。

**Comment by pansystar** [comment]
なるほど...

VPNに限らず今回のケースは発生する可能性が高いため、鯖側の修正に少し時間を頂きたく思います。

ひとまず
* 警告の表示(エラーコード詳細ページに促す処理を検討中)
を先行して設計しようと思います。

**Comment by Reiya0917milk** [comment]
今段階では認証できるようになったためｸﾛｰｽﾞ

**Comment by pansystar** [comment]
申し訳ございません。

改めて設計し直します。

**Comment by pansystar** [comment]
#９０ 関連
