### ISSUE TITLE
何故か音源が再生されない

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#37]
何故か音源が再生されません
https://ux.getuploader.com/n_make_taiko2/download/27

**Comment by pansystar** [comment]
DLLすると文字化けしたファイルになっていました。

TJA内の音源ファイル名は正常だったためファイル名が異なるという理由で
再生がされなかったものと思います。

![image](https://user-images.githubusercontent.com/17560479/107446543-07759900-6b82-11eb-84bf-be8206566495.png)
