### ISSUE TITLE
風船の表示がおかしい

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#38]
![image](https://user-images.githubusercontent.com/77183438/107630692-405b5e00-6ca7-11eb-911b-fca8a1095941.png)

https://www.axfc.net/u/2849265
https://www.axfc.net/u/3054083.zip

**Comment by pansystar** [comment]
再現しました。
(不覚にも笑ってしまいました。)

**Comment by pansystar** [comment]
風船(7)が連続している譜面のときにこの挙動になる模様。

**Comment by pansystar** [comment]
対応完了 v0.2.0で公開
