### ISSUE TITLE
シンクライアント用PCでファイルをレジストリで指定して起動しようとするとエラーが発生する

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#46]
シンクライアント用PCでプレイしたいため
![IMG_20210220_010050](https://user-images.githubusercontent.com/77183438/108528886-3e347780-7317-11eb-9b6f-919a2ba97937.jpg)

**Comment by pansystar** [comment]
原因はわかるため、早期修正する。
v0.2.2を配布予定。

**Comment by pansystar** [comment]
対応
