### ISSUE TITLE
太鼓フォースの入力信号を割当できるように

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#47]

**Comment by pansystar** [comment]
入力信号に関する資料があれば対応しますが、現状わかりません。

**Comment by Reiya0917milk** [comment]
ここら変動でしょうか？
https://github.com/AioiLight/TJAPlayer3/blob/master/TJAPlayer3/Stages/04.Config/CActConfigKeyAssign.cs

**Comment by Reiya0917milk** [comment]
手動で割り当てたためclose
