### ISSUE TITLE
一部の譜面でジャンルを指定するとエラーが発生する

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#50]
![image](https://user-images.githubusercontent.com/77183438/109303690-7fc8a380-787e-11eb-9644-b887a9986e29.png)

**Comment by pansystar** [comment]
エラー理由は分かりましたが、原因は現状不明です。

次回公開時にログを強化します。

ひとまず暫定的な対処になりますが、該当の譜面がわかる場合は、そのファイルをテキストエディタで開き、文字コードを別のエンコードに変更してください。

**Comment by pansystar** [comment]
@Reiya0917milk 
こちらの現象は、TJAファイルでGENREを指定しなければ、
問題なく動作するという認識で合ってますでしょうか？

**Comment by Reiya0917milk** [comment]
そうです。そちらで再現されるかどうかを確認できませんでしょうか？
[006 sweet & sweet holiday.zip](https://github.com/Tatelier/Tatelier/files/6172544/006.sweet.sweet.holiday.zip)

**Comment by pansystar** [comment]
@Reiya0917milk ありがとうございます。原因がわかり解消策がわかりました。
v0.3.0で公開します。

**Comment by pansystar** [comment]
## 原因
エンコード判定処理で、utfとeucの結果が一致してしまい、どっちのエンコードにすればわからず、nullを返していた。
