### ISSUE TITLE
演奏画面にAVI動画の再生

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#62]
可能であれば実装お願いします。
https://github.com/AioiLight/TJAPlayer3/blob/master/TJAPlayer3/Stages/07.Game/CAct%E6%BC%94%E5%A5%8FAVI.cs

**Comment by pansystar** [comment]
検討

**Comment by Reiya0917milk** [comment]
動作が遅くなる可能性があるためとりあえずはクローズ
既知の問題が解消次第リオープンする可能性あり。
