### ISSUE TITLE
WAVE指定をしてないtjaファイルを読み込もうとすると、エラーが発生する

### ISSUE THREAD

**Issue by Hagane1152** [Tatelier/Tatelier#64]

**Comment by pansystar** [comment]
音源なしでも遊べるようにする。

**Comment by Hagane1152** [comment]
再生に使用した譜面です。
TITLE:test
BPM:100
WAVE:
GENRE:バラエティ
OFFSET:0
COURSE:Oni
LEVEL:10
BALLOON:10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
SCOREINIT:1000000000
SCOREDIFF:72389876543
#START
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
#GOGOSTART
0101010101020202,
#GOGOEND
0101010101020202,
#GOGOSTART
0101010101020202,
#GOGOEND
0101010101020202,
GOGOSTART
#BPMCHANGE 300
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
111111111111111111111111,
0101010101020202,
0101010101020202,
0101010101020202,
#BPMCHANGE 600
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
111111111111111111111111,
0101010101020202,
0101010101020202,
0101010101020202,
#BPMCHANGE 1000
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
111111111111111111111111,
#GOGOEND
0101010101020202,
0101010101020202,
0101010101020202,
#GOGOSTART
#BPMCHANGE 1000
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
0101010101020202,
111111111111111111111111,
0202,
111111111111111111111111,
111111111111111111111111,
500000000000000000000000,
000000000000000000000000,
000000000000000000000008,
#GOGOEND
#GOGOSTART
#BPMCHANGE 300
500000000000000000000000,
000000000000000000000000,
500000000000000000000000,
000000000000000000000000,
500000000000000000000000,
000000000000000000000000,
500000000000000000000000,
000000000000000000000000,
500000000000000000000000,
000000000000000000000000,
500000000000000000000000,
000000000000000000000008,
787878787878787878778780,
111111111111111111111111,
111111111111111111111111,
#BPMCHANGE -300
111111111111111111111111,
111111111111111111111111,
#GOGOEND
#END

**Comment by pansystar** [comment]
修正済み
v0.3.1で公開

@Hagane1152 
該当の譜面はbpmがマイナス値になったときの不具合も併発すると思われます。
別Issueで対応します。
