### ISSUE TITLE
エラー画面から再起動すると、選曲画面がおかしくなる

### ISSUE THREAD

**Issue by Hagane1152** [Tatelier/Tatelier#66]
エラー画面から再起動すると、選曲画面がおかしくなる
https://i.gyazo.com/e630d9d2af753ab2f78307b0f7b531a6.png
↑こんな感じ

**Comment by Hagane1152** [comment]
たぶん治ったのでClose。

**Comment by pansystar** [comment]
再起動時の管理処理に不具合がある模様。

**Comment by pansystar** [comment]
再起動時にリセットするデータを整理し修正。
v0.4.0にて公開
