### ISSUE TITLE
デモ音源が再生されないのと演奏画面に移動できない(音声の読み込みの不具合だと思われる)

### ISSUE THREAD

**Issue by Takkkom** [Tatelier/Tatelier#68]
ここで譜面をDLしました(リンクは作者のyoutubeの動画のリンクを張らせていただきます) 
https://www.youtube.com/watch?v=LhrCdk1yI2Y 
おそらく音源のメモリへの読み込みは成功しているけどTatelier特有の音源の処理を行っている影響だと思われます 
こちらで事前に通常の方法でDxLibでの再生の成功を確認しています 
以下動作確認と再生の成功の確認の環境

ハードウェア
OS Windows10 Pro 64bit
CPU Intel i5-3470s 
GPU NVIDIA Geforce GTX1050Ti
Ram 16GB DDR3

こちらソフトウェア
DxLibのバージョン 3.22a
.netframeworkのバージョン 4.8
DxLibのラッパーなどは使用してません

**Comment by pansystar** [comment]
現象を確認しました。

リンクのzipはmacで作成されているみたいです。

macで適切な設定で圧縮されていればwindows標準でも通常通り展開できるのですが、
このzipはその設定がされていないため、譜面ファイルに記述されている音源パスとエクスプローラからみたファイルパスが一致せず、音源が見つけられていません。

//WAVE
![abc (1)](https://user-images.githubusercontent.com/17560479/113288616-2abef800-932a-11eb-8b51-536c83750f78.gif)

この譜面で遊ぶ場合は
- 音源ファイルのパスを変更する
- 譜面側のパスを変更する
のどちらかで遊べるようになるのでお試しください。


ps.
ただ、音源がないと例外になるのは不具合なので直します！報告ありがとうございました！

**Comment by pansystar** [comment]
#64 関連
