### ISSUE TITLE
BPMマイナスの処理の対応

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#71]
参考資料
https://github.com/AioiLight/TJAPlayer3/pull/299/files
https://github.com/AioiLight/TJAPlayer3/pull/346/files

**Comment by pansystar** [comment]
負値のBPMがパース時に見つかった場合はダイアログで警告する。(演奏不可)

**Comment by Reiya0917milk** [comment]
警告は[#27](https://github.com/Tatelier/Tatelier/issues/27)で対応されていると思われますのでプレイできるようにすることはできないでしょうか？

**Comment by pansystar** [comment]
なるほど....

こういう動作をしてほしいという要望はありますか？
実際に使われている譜面やその挙動が見れる動画があると
開発に踏み切れるかもしれません。

リンクに貼っていただいたソースを見たのですが、考え方が異なるためそのまま活かすのは難しそうです。

**Comment by Reiya0917milk** [comment]
仕様に関しては次郎に寄せてください。
https://ux.getuploader.com/LoveLive_Jiro/download/112
https://ux.getuploader.com/LoveLive_SpSt_Jiro/download/1
https://ux.getuploader.com/LoveLive_SS_Jiro/download/45

**Comment by pansystar** [comment]
ありがとうございます。

参考にします。

**Comment by pansystar** [comment]
マイナスの処理はHBSCROLLかそうでないかで、挙動を変えるようにする。

|なし|あり|
|:---|:---|
|負値を正に変換して普通の挙動にする。|次郎のHBSCROLLを参考とした挙動にする|

**Comment by pansystar** [comment]
#80 関連

**Comment by pansystar** [comment]
@Reiya0917milk 

HBSCROLLの暫定対応版になります。
https://tatelier.pansystar.net/dist/dbg/Tatelier-v0.3.1d2.zip

**Comment by pansystar** [comment]
#81 関連

**Comment by pansystar** [comment]
別チケットにて処理するため、本チケットはクローズ
