### ISSUE TITLE
譜面分岐曲終了後にリザルト画面に移行しない

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#74]
[T.O.P. -SonicX-.zip](https://github.com/Tatelier/Tatelier/files/6272086/T.O.P.-SonicX-.zip)

**Comment by pansystar** [comment]
現象を確認しました。

どうやら分岐譜面に限らず、この音源のときに、ライブラリ側が最後まで音声を流さずに終了することで
Tatelierの音声終了処理が作動せず、演奏画面に取り残されることがわかりました。

最後に無音が数秒あるとこのような動作になるのかもしれません。
改めて調査するため、v0.4.0へ盛り込むのは難しいです。ごめんなさい！

別チケットで対応を検討していきます。

**Comment by pansystar** [comment]
#83

**Comment by pansystar** [comment]
ひとまずクローズ
