### ISSUE TITLE
TJA譜面作成ツールでTatelier.exeを指定してツールで実行をした時に編集画面に移行するようにしてほしい

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#76]
[TJAStudio](https://aioilight.space/tjastudio/download/)
[譜面エディタ](https://wikiwiki.jp/jiro/%E8%A3%BD%E4%BD%9C%E6%94%AF%E6%8F%B4%E3%83%84%E3%83%BC%E3%83%AB)

**Comment by pansystar** [comment]
TJAStudioのシミュ実行を見てみましたが、シミュがファイルパスをもらうだけのようなので実現は可能です。

人によっては編集よりも演奏がしたいというケースもあり得るため、ファイルパスをもらったときの挙動をMainConfig.hjsonで指定できるように実装を進めたいと思います。

https://github.com/AioiLight/TJAStudio/search?q=SimulatorPath

**Comment by pansystar** [comment]
ファイルパス指定やD&Dによる譜面実行処理が未実装のため、v0.5.0では見送らせてください。

すいません。
