### ISSUE TITLE
HBSCROLLで一部挙動が異なる

### ISSUE THREAD

**Issue by pansystar** [Tatelier/Tatelier#80]
- [x] 連打音符の描画
- [x] 風船音符の描画
- [x] 音符がない小節の後の描画

#78 関連

**Comment by pansystar** [comment]
難航中。

**Comment by Reiya0917milk** [comment]
譜面の製作者さんから少し解説をいただけたので一応書いておきます。
PSYCHIC FIREの譜面の41小節あたりからのBメロ辺り。
まずはHBSCROLLを指定した状態でBPMとMEASUREをマイナスに指定すると、その位置から譜面が突然逆向きに流れるようになります。
音符が突然現れる現象については原理不明のバグを使用しています。
#BPMCHANGE 169
#MEASURE 8/1
000,
#BPMCHANGE -169
000,
突然現れるようにしたい小節の直前にこのようなBPM変化を入れると、入れたMEASUREの長さに応じて譜面が突然現れます。

**Comment by pansystar** [comment]
次郎の描画アルゴリズムをなんとか分析しないといけないですね...

考えてみます！

**Comment by Reiya0917milk** [comment]
MEASUREの位置で逆走しているということですのでMEASUREの部分を変更してみるのはどうでしょうか？

**Comment by pansystar** [comment]
BPM変化を除いたら今のTatelierと同じ挙動になりました。
...なかなか難しい問題ですね...

**Comment by pansystar** [comment]
少しずつ見えてきました...
どのように処理するかはまだですが...

**Comment by pansystar** [comment]
#117 別チケットで管理

**Comment by Reiya0917milk** [comment]
ほかの方が開設してくださっていますので良ければ
https://twitter.com/CurryDry0608hk/status/1256129213712617473

**Comment by pansystar** [comment]
v0.6.2で公開。
一部処理が次郎と異なるが、その際は別チケットを作成して対応する。
