### ISSUE TITLE
譜面分岐が切り替わった後に譜面が流れてこない

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#82]
裏譜面
[007 元気全開DAY! DAY! DAY!.zip](https://github.com/Tatelier/Tatelier/files/6336908/007.DAY.DAY.DAY.zip)

**Comment by pansystar** [comment]
事象確認。

原因調査中。

**Comment by pansystar** [comment]
理由判明。

分岐処理のタイミングは、#BRANCHSTARTの1小節前の時間になったら実行されるが、複数の分岐の感覚が狭いとき、このような挙動になる模様。

対応する。

**Comment by pansystar** [comment]
対応完了。

ただ、表示は次郎と異なる挙動をしています。
v0.5.0で公開
