### ISSUE TITLE
音源ファイルが読み込みできない曲がある

### ISSUE THREAD

**Issue by Reiya0917milk** [Tatelier/Tatelier#84]
[バラライカ.zip](https://github.com/Tatelier/Tatelier/files/6365840/default.zip)

**Comment by pansystar** [comment]
自分の環境(ほぼv0.4.0)では再生されました。
音源ファイル読み込み部は特に処理を変えてないので謎ですね...

v0.4.0を公開しましたら改めて動画を確認いただきたく思います。

**Comment by Reiya0917milk** [comment]
v0.4.0で動作確認をしたらエラーが出ました
![image](https://user-images.githubusercontent.com/77183438/115980765-1c32cc00-a5ca-11eb-9caf-0067978c1999.png)

**Comment by Reiya0917milk** [comment]
問題なく再生できました。

**Comment by pansystar** [comment]
@Reiya0917milk 
もし原因がわかりましたら書いていただけると非常に嬉しいです。

**Comment by Reiya0917milk** [comment]
譜面を再度入れなおしたら動きました
